### ISSUE TITLE
How can I have a trial?

### ISSUE THREAD

**Issue by DiligentCatCat** [fiatrete/SDCN-Stable-Diffusion-Computing-Network#1]
Hi, I'm very interested in this project. I notice that the domain field in requesting-url in the examples are replaced by `SDCN_SERVER`, is there an existing domain, so that I can have a trial?

**Comment by fiatrete** [comment]
The API service has just published in https://api.sdcn.info . Fire a issue if you have any problem calling the service.
Many thanks to @maxwilliamdev for generously donating two high-performance GPU servers(RTX 3090 24GB).
