### ISSUE TITLE
[discuss] Migrating to an other language?

### ISSUE THREAD

**Issue by DiligentCatCat** [fiatrete/SDCN-Stable-Diffusion-Computing-Network#18]
Hi. Do you have plan to migrate SDCN server to another language, such as golang, java, kotlin, C# or javascript/typescript? The current implementation looks a bit temporary? (I apologize if this is not truth)

For my own feeling, I want to do some contribution, but since I'm not very familiar with openresty and lua is a dynamic-typed language, it's very hard for me to get involve. By migrating to a static-typed language, for those unfamiliar with the language/framework, it will be easier to get involve since many editors will give them hints. And, a more popular language/framework will have more folks, it's also good for community development.

**Comment by fiatrete** [comment]
Well yes, I am planning to rewrite `sdcn-server` based on a more formal backend development framework. Based on current research, TypeScript may be a good choice.  If you have any suggestions or ideas, please let me know.

**Comment by DiligentCatCat** [comment]
Sounds good! Let me try to port the implementation to TypeScript! :-) 

And... do you have a road map?

**Comment by fiatrete** [comment]
roadmap is updated in readme.
