### ISSUE TITLE
Where can I find LoRA and Model IDs?

### ISSUE THREAD

**Issue by DiligentCatCat** [fiatrete/SDCN-Stable-Diffusion-Computing-Network#2]
Hi, I tried your example, the result looks great!

But there are some magic string in your example code. e.g. `loras` and `model` seems to be/contain some sort of hash.

So what do these hashes mean? Is there a list of valid candidates?

**Comment by fiatrete** [comment]
Oops!
It's in `config.lua`. I'm thinking of including it into the documents.
<img width="779" alt="image" src="https://user-images.githubusercontent.com/126534313/224914453-cc84f3b9-bcfb-49d8-8dad-6164de8a534e.png">
These are my most used models and loras. more model can be supported if needed.
